#!/bin/zsh

alias ls='ls --color=auto'
alias ll='ls -alh'

alias grep='grep --color=auto'

alias vi='nvim'
alias vim='nvim'

alias 4k='xrandr --output DP-0 --primary --mode 3840x2160 --scale 1x1'
alias hd='xrandr --output DP-0 --primary --mode 3840x2160 --scale-from 1920x1080'
