#!/bin/zsh

# TODO: Find a way to properly highlight ZLE's Vi visual mode.
#       https://github.com/zsh-users/zsh-syntax-highlighting/issues/887

# Source "zsh-syntax-highlighting" plugin that should be installed on the system.
source "/usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

# TODO Use "brackets" highlighter when it:
#      - Stops overriding "main" highlighter's colors for delimiters which use paranthesis - $(), $(()), <().
#        https://github.com/zsh-users/zsh-syntax-highlighting/issues/889
#
#      - Stops highlighting tha last visited paranthesis after entering ZLE's Vi insert mode.
#        https://github.com/zsh-users/zsh-syntax-highlighting/issues/890

# Define which syntax highlighters will be used from "zsh-syntax-highlighting".
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main)

# Define the style of "main" highlighter.
ZSH_HIGHLIGHT_STYLES[default]='none'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=red'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=magenta'
ZSH_HIGHLIGHT_STYLES[alias]='fg=blue'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=blue,underline'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg=blue,underline'
ZSH_HIGHLIGHT_STYLES[builtin]='fg=blue'
ZSH_HIGHLIGHT_STYLES[function]='fg=blue'
ZSH_HIGHLIGHT_STYLES[command]='fg=blue'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=blue,underline'
ZSH_HIGHLIGHT_STYLES[commandseparator]='none'
ZSH_HIGHLIGHT_STYLES[hashed-command]=''
ZSH_HIGHLIGHT_STYLES[autodirectory]=''
ZSH_HIGHLIGHT_STYLES[path]='underline'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]=''
ZSH_HIGHLIGHT_STYLES[path_prefix]=''
ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]=''
ZSH_HIGHLIGHT_STYLES[globbing]='fg=cyan'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=cyan'
ZSH_HIGHLIGHT_STYLES[command-substitution]='none'
ZSH_HIGHLIGHT_STYLES[command-substitution-unquoted]='none'
ZSH_HIGHLIGHT_STYLES[command-substitution-quoted]='none'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]='fg=magenta'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-unquoted]='fg=magenta'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-quoted]='fg=magenta'
ZSH_HIGHLIGHT_STYLES[process-substitution]='none'
ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]='fg=magenta'

# TODO: Bug: Arithmetic highlighting is not working at all.
#       https://github.com/zsh-users/zsh-syntax-highlighting/issues/888
#ZSH_HIGHLIGHT_STYLES[arithmetic-expansion]='fg=cyan'

ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#4EC9B0'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#4EC9B0'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='bg=red'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-unclosed]='bg=red'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-delimiter]='bg=red'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#CE9178'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#CE9178'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#CE9178'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#CE9178'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#CE9178'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#CE9178'
ZSH_HIGHLIGHT_STYLES[rc-quote]=''
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=cyan'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=white'
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=white'
ZSH_HIGHLIGHT_STYLES[assign]='none'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=yellow'
ZSH_HIGHLIGHT_STYLES[comment]='fg=green'
ZSH_HIGHLIGHT_STYLES[named-fd]='fg=yellow'
ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg=yellow'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=blue'
